# Note: Shank does not support the ".workspace" notation, so the values
# are duplicated here. This limitation will be addressed when we upgrade
# to use Codama macros.

[package]
name = "ore-api"
description = "API for interacting with the ORE program"
version = "2.3.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply"
documentation = "https://ore.supply"
repository = "https://github.com/regolith-labs/ore"
readme = "./README.md"
keywords = ["solana", "crypto", "mining"]

[dependencies]
array-const-fn-init = "0.1.1"
bytemuck = "1.14.3"
const-crypto = "0.1.0"
drillx = { version = "2.0.0", features = ["solana"] }
mpl-token-metadata = "4.1.2"
num_enum = "0.7.2"
solana-program = "^1.18"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^2.3", features = [ "no-entrypoint" ] } 
static_assertions = "1.1.0"
steel = { features = ["spl"], version = "1.0" }
thiserror = "1.0.57"
shank = "0.4.2"

[package.metadata.solana]
program-id = "oreV2ZymfyeXgNgBdqMkumTqqAprVqgBWQfoYkrtKWQ"
